included:
  - BlueIntentCore/Classes

disabled_rules:
  - force_cast
  - force_try
  - identifier_name
  - type_name
  - file_length
  - line_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - trailing_whitespace